print(complex(3,4))
print(complex(0,4))
print(complex(3))
print(complex(3.8 , 4.6))
print(complex(3,4.5))
print(complex(True , False))
print(complex(True))
print(complex(False))
print(complex(True,4))
print(complex('3'))
print(complex('3.8'))
#print(complex(3,'4'))
#print(complex('3',4))
#print(complex('3','4'))
#print(complex('Ten'))