print(bool(0))
print(bool(10))
print(bool(-25))
print(bool(0.0))
print(bool(0.1))
print(bool(0+0j))
print(bool(10+20j))
print(bool(-15j))
print(bool('False'))
print(bool(''))
print(bool('Hyd'))
print(bool(' '))
print(bool('True'))