#and operator
print(True and False)
print(False and True)
print(False and False)
print(True and True)
print(10 and 20)
print(0 and 20)
print(-25 and 0)
print('' and 25)
print(6j and 'Hyd')
print(0j and 'Hyd')
print('Hyd' and 10.8)
print(10 and 20 and 30)
print()
#or operator
print(True or False)
print(False or True)
print(True or True)
print(False or False)
print(10 or 20)
print(0 or 20)
print(-25 or 0)
print('' or 35)
print(6j or 'Hyd')
print(0.0 or 3+4j)
print('Hyd' or 10.8)
print()
#not operator
print(not True)
print(not False)
print(not 25)
print(not 0)
print(not 'Hyd')
print(not '')
print(not -10)
print(not not 'Hyd')
print()
#output
i=10
i=not i>14
print(i)
print(not(6<4 or 9>=5 and 6!=6))