list=[10,20,15,12,18]
print(15 in list)
print(19 in list)
print(14 not in list)
print(15 not in list)
s='Hyd is green city'
print('is' in s)
print('was' in s)
print('g' in s)
print('z' in s)
print(' ' in s)
print('gre' in s)
print('yd i' in s)
print('' in s)
print('' not in s)