# eval()  function  demo  program
print(eval('25'))
print(eval('10.8'))
print(eval('False'))
print(eval('3+4j'))
#print(eval('Hyd'))
print(eval("    'Hyd'   "))
print(eval('3 + 4 * 5'))
print(eval('[10 , 20 , 15 , 18]'))
print(eval('{10,20,15,18,20,12,18}'))
print(eval('(10 , 20 , 30)'))
print(eval("{10 : 'Hyd' , 10 : 'Sec'}"))
#print(eval(4 + 5))
print()
#  assignment 2
print(eval("    'hyd'   "))
hyd = 'Sec'
print(eval('hyd'))
sec = '25'
print(eval('sec'))
print(eval(sec))
cyb = 10.8
print(eval('cyb'))
#print(eval(cyb))
print()
#  Find  output  (Home  work)
print(eval('print("Hyd")'))
print()
#  Find  outputs  (Home  work)
print(bool('False'))
print(eval('False'))
print(bool(''))
print(eval('  ""  '))
#print(eval(''))            #converts '' to nothing
print(eval('  " "   '))
#print(eval(' '))             #converts ' ' to nothing
print()
# What  is  the  advantage  of  eval(input()) ?
x = eval(input('Enter  any  input  :  '))
print(type(x))
print(x)
print()
# What  is  a  better  approach  to  read  string  input ?
a = input('Enter  any  string  :  ')
print(len(a))
print(a)
b = eval(input('Enter   any  string  : '))
print(len(b))
print(b)
print()
